######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : pegasus_io_test, Index = 0, Count = null
# SUBMIT FILE NAME : clean_up_condorpool_level_3_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "PATH=/home/hariharan/software/spack/var/spack/environments/mimir-build/.spack-env/view/bin:/home/hariharan/software/spack/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=820f9232-f917-42c0-8dde-b4076426d3a1 PEGASUS_WF_LABEL=pegasus_io_test PEGASUS_DAG_JOB_ID=clean_up_condorpool_level_3_0 PEGASUS_SITE=local"
arguments = " -n pegasus::cleanup -N null -i - -R local -L pegasus_io_test -T 2022-02-21T12:45:55-08:00 /usr/bin/../bin/pegasus-transfer "
error = /home/hariharan/CLionProjects/mimir/test/posix/pegasus/pegasus/work/hariharan/pegasus/pegasus_io_test/run0001//00/00/clean_up_condorpool_level_3_0.err
executable = /usr/bin/../bin/pegasus-kickstart
input = /home/hariharan/CLionProjects/mimir/test/posix/pegasus/pegasus/work/hariharan/pegasus/pegasus_io_test/run0001//00/00/clean_up_condorpool_level_3_0.in
log = /home/hariharan/CLionProjects/mimir/test/posix/pegasus/pegasus/work/hariharan/pegasus/pegasus_io_test/run0001/pegasus_io_test-0.log
notification = NEVER
output = /home/hariharan/CLionProjects/mimir/test/posix/pegasus/pegasus/work/hariharan/pegasus/pegasus_io_test/run0001//00/00/clean_up_condorpool_level_3_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 1000
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "820f9232-f917-42c0-8dde-b4076426d3a1"
+pegasus_wf_uuid = "820f9232-f917-42c0-8dde-b4076426d3a1"
+pegasus_version = "5.0.1"
+pegasus_wf_name = "pegasus_io_test-0"
+pegasus_wf_time = "20220221T124555-0800"
+pegasus_wf_xformation = "pegasus::cleanup"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "clean_up_condorpool_level_3_0"
+pegasus_job_class = 8
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_gpus = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
