######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : pegasus_io_test, Index = 0, Count = null
# SUBMIT FILE NAME : pegasus_write_ID0000002.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PEGASUS_HOME=/usr CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=820f9232-f917-42c0-8dde-b4076426d3a1 PEGASUS_WF_LABEL=pegasus_io_test PEGASUS_DAG_JOB_ID=pegasus_write_ID0000002 PEGASUS_SITE=condorpool PEGASUS_SCRATCH_DIR=/home/hariharan/CLionProjects/mimir/test/posix/pegasus/scratch/hariharan/pegasus/pegasus_io_test/run0001"
+WantIOProxy = True
arguments = " -n pegasus_write -N ID0000002 -R condorpool -L pegasus_io_test -T 2022-02-21T12:45:55-08:00 /home/hariharan/CLionProjects/mimir/build/test/posix/pegasus --durations yes --reporter compact --pfs /home/hariharan/temp/mimir/pfs --shm /home/hariharan/temp/mimir/shm --filename write_job.dat [operation=write]"
error = /home/hariharan/CLionProjects/mimir/test/posix/pegasus/pegasus/work/hariharan/pegasus/pegasus_io_test/run0001//00/00/pegasus_write_ID0000002.err
executable = /usr/bin/pegasus-kickstart
log = /home/hariharan/CLionProjects/mimir/test/posix/pegasus/pegasus/work/hariharan/pegasus/pegasus_io_test/run0001/pegasus_io_test-0.log
notification = NEVER
output = /home/hariharan/CLionProjects/mimir/test/posix/pegasus/pegasus/work/hariharan/pegasus/pegasus_io_test/run0001//00/00/pegasus_write_ID0000002.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 10
remote_initialdir = /home/hariharan/CLionProjects/mimir/test/posix/pegasus/scratch/hariharan/pegasus/pegasus_io_test/run0001
submit_event_user_notes = pool:condorpool
transfer_executable = false
universe = vanilla
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "820f9232-f917-42c0-8dde-b4076426d3a1"
+pegasus_wf_uuid = "820f9232-f917-42c0-8dde-b4076426d3a1"
+pegasus_version = "5.0.1"
+pegasus_wf_name = "pegasus_io_test-0"
+pegasus_wf_time = "20220221T124555-0800"
+pegasus_wf_xformation = "pegasus_write"
+pegasus_wf_dax_job_id = "ID0000002"
+pegasus_wf_dag_job_id = "pegasus_write_ID0000002"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_gpus = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
